version: '3'

services:

  mysql:
    image: mariadb
    container_name: miac
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=miac_db
    ports:
      - "3307:3306"


